### ISSUE TITLE
SIGTRAP

### ISSUE THREAD

**Issue by petterssonjonas** [wheybags/wcp#3]
cloned and built according to instructions, then ran program:

ASSERTION FAILED: (argc == 3) in /home/fuze/code/gits/wcp/src/wcpMain.cpp:23
fish: Job 1, './wcp' terminated by signal SIGTRAP (Trace or breakpoint trap)

Running up to date Arch.

**Comment by wheybags** [comment]
Ah yeah, you need to give it some arguments. At the moment it just asserts that there are two arguments. It should probably print a usage message.

**Comment by wheybags** [comment]
https://github.com/wheybags/wcp/commit/e1023491f8d748d26eb44a74f4318083caedfa31 adds a more friendly error message. Thanks for the report!
