### ISSUE TITLE
Segfault when copying directories

### ISSUE THREAD

**Issue by VitorTrin** [wheybags/wcp#4]
when copying directories, I receive a segfault.

```bash
mkdir a
mkdir b
wcp a b

[1]    7072 segmentation fault (core dumped)  wcp a b               0.00 B / ???                                     8388608.00 TiB/s   ETA: ???
```

I understand this program doesn't support directories? It would be nice to give an error instead of segfaulting

**Comment by wheybags** [comment]
No, it does definitely support directories, the issue is probably a bug when the source directory is empty. Will look into it, thanks for the report!

**Comment by wheybags** [comment]
Should be fixed by https://github.com/wheybags/wcp/commit/fbc63458fc3a9f7dd122429b97072b3863624bde
Let me know if you have any more problems!
