### ISSUE TITLE
Compilation Error on Debian 10

### ISSUE THREAD

**Issue by Erreur32** [wheybags/wcp#5]

**Comment by Erreur32** [comment]
i'm on  Debian 4.19.171-2 

i've follow your build information:

## Build instructions

```
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release make
```

And  i have this error on **MAKE** : 

```
# make
Scanning dependencies of target Uring
[  5%] Building C object liburing/CMakeFiles/Uring.dir/src/setup.c.o
/home/tools/wcp/liburing/src/setup.c:13:10: fatal error: liburing/compat.h: Aucun fichier ou dossier de ce type
 #include "liburing/compat.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [liburing/CMakeFiles/Uring.dir/build.make:63: liburing/CMakeFiles/Uring.dir/src/setup.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:204: liburing/CMakeFiles/Uring.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

What can i do or i missed something ?

**Comment by wheybags** [comment]
I believe this should fix it https://github.com/wheybags/wcp/commit/dbe26be3ac0c8f74136bed63bcd51baa6659e320 
Let me know if it's still not working for you.

**Comment by Erreur32** [comment]
With the latest version i still have some issue.

/wcp/build (master)# make

`[ 26%] Built target Uring`  
`Scanning dependencies of target wcp_lib`  
`[ 31%] Building CXX object CMakeFiles/wcp_lib.dir/src/CopyRunner.cpp.o`  
`[ 36%] Building CXX object CMakeFiles/wcp_lib.dir/src/CopyQueue.cpp.o`  
`[ 42%] Building CXX object CMakeFiles/wcp_lib.dir/src/Util.cpp.o`  
`/home/tools/Bash_Source/wcp/src/Util.cpp: In lambda function:`  
`/home/tools/Bash_Source/wcp/src/Util.cpp:101:18: error: ‘getdents64’ was not declared in this scope`  
`retval = getdents64(dfd, buffer, bufferSize);`  
`^~~~~~~~~~`  
`/home/tools/Bash_Source/wcp/src/Util.cpp:101:18: note: suggested alternative: ‘getdirentries64’`  
`retval = getdents64(dfd, buffer, bufferSize);`  
`^~~~~~~~~~`  
`getdirentries64`  
`make[2]: *** [CMakeFiles/wcp_lib.dir/build.make:115: CMakeFiles/wcp_lib.dir/src/Util.cpp.o] Error 1`  
`make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/wcp_lib.dir/all] Error 2`  
`make: *** [Makefile:84: all] Error 2`

Do i need to reopen a Ticket ?
