### ISSUE TITLE
Segfault after (successfully) copying a file

### ISSUE THREAD

**Issue by TheLostWanderer** [wheybags/wcp#6]
Tried copying the generated makefile in the build dir. It copies it and then segfault.

```
➜  build git:(master) ./wcp ./Makefile ./makefile2

[1]    84267 segmentation fault (core dumped)  ./wcp ./Makefile ./makefile2                    0.00 B / ???                                                                8388608.00 TiB/s   ETA: ??? 

➜  build git:(master) sha256sum Makefile makefile2 
e5d39c95e249cabb61523b2d5053a17524c632062d55362b746c1d744568ae48  Makefile
e5d39c95e249cabb61523b2d5053a17524c632062d55362b746c1d744568ae48  makefile2

➜  build git:(master) 
```

Using up to date arch linux with linux-zen `5.11.2-zen1-1-zen`, compiled using `commit 641e5ef9d` (latest as of the time of writing).

**Comment by simao** [comment]
I have the same problem, archlinux using `linux 5.11.2-arch1-1`. Using latest wcp.

**Comment by wheybags** [comment]
Should be fixed by https://github.com/wheybags/wcp/commit/fbc63458fc3a9f7dd122429b97072b3863624bde
Let me know if you have any more problems!

**Comment by simao** [comment]
works for me now. thanks for fixing it!
