### ISSUE TITLE
Unhandled file type 10

### ISSUE THREAD

**Issue by rytec-nl** [wheybags/wcp#8]
Hi,

I tried your tool as it looks really promising. When doing so I get a lot of `Unhandled file type: "" 10` errors, looking into it type 10 seems to be symbolic links.

Do you plan to add support for symlinks? 

Thanks in advance!

**Comment by wheybags** [comment]
Symlinks should be working now: https://github.com/wheybags/wcp/commit/341ad3b8d88b5ca90e5892d06a4944d31e2b501b

**Comment by wheybags** [comment]
Thanks for the report!

**Comment by rytec-nl** [comment]
Thanks! Works perfectly!
